#pragma once

// @generated by torchgen/gen.py from Function.h

#include <ATen/Context.h>
#include <ATen/DeviceGuard.h>
#include <ATen/TensorUtils.h>
#include <ATen/TracerMode.h>
#include <ATen/core/Generator.h>
#include <ATen/core/Reduction.h>
#include <ATen/core/Tensor.h>
#include <c10/core/Scalar.h>
#include <c10/core/Storage.h>
#include <c10/core/TensorOptions.h>
#include <c10/util/Deprecated.h>
#include <c10/util/Optional.h>



#include <ATen/ops/_reshape_nested_ops.h>

namespace at {


// aten::_reshape_nested(Tensor self, int[] shape) -> Tensor
inline at::Tensor _reshape_nested(const at::Tensor & self, at::IntArrayRef shape) {
    return at::_ops::_reshape_nested::call(self, shape);
}

// aten::_reshape_nested.out(Tensor self, int[] shape, *, Tensor(a!) out) -> Tensor(a!)
inline at::Tensor & _reshape_nested_out(at::Tensor & out, const at::Tensor & self, at::IntArrayRef shape) {
    return at::_ops::_reshape_nested_out::call(self, shape, out);
}

// aten::_reshape_nested.out(Tensor self, int[] shape, *, Tensor(a!) out) -> Tensor(a!)
inline at::Tensor & _reshape_nested_outf(const at::Tensor & self, at::IntArrayRef shape, at::Tensor & out) {
    return at::_ops::_reshape_nested_out::call(self, shape, out);
}

}
