#pragma once

// @generated by torchgen/gen.py from Function.h

#include <ATen/Context.h>
#include <ATen/DeviceGuard.h>
#include <ATen/TensorUtils.h>
#include <ATen/TracerMode.h>
#include <ATen/core/Generator.h>
#include <ATen/core/Reduction.h>
#include <ATen/core/Tensor.h>
#include <c10/core/Scalar.h>
#include <c10/core/Storage.h>
#include <c10/core/TensorOptions.h>
#include <c10/util/Deprecated.h>
#include <c10/util/Optional.h>



#include <ATen/ops/_reshape_nested_backward_ops.h>

namespace at {


// aten::_reshape_nested_backward(Tensor self, Tensor grad) -> Tensor
inline at::Tensor _reshape_nested_backward(const at::Tensor & self, const at::Tensor & grad) {
    return at::_ops::_reshape_nested_backward::call(self, grad);
}

// aten::_reshape_nested_backward.out(Tensor self, Tensor grad, *, Tensor(a!) out) -> Tensor(a!)
inline at::Tensor & _reshape_nested_backward_out(at::Tensor & out, const at::Tensor & self, const at::Tensor & grad) {
    return at::_ops::_reshape_nested_backward_out::call(self, grad, out);
}

// aten::_reshape_nested_backward.out(Tensor self, Tensor grad, *, Tensor(a!) out) -> Tensor(a!)
inline at::Tensor & _reshape_nested_backward_outf(const at::Tensor & self, const at::Tensor & grad, at::Tensor & out) {
    return at::_ops::_reshape_nested_backward_out::call(self, grad, out);
}

}
